variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    DEVELOPMENT_BRANCH: 'trunk'
    PLATFORM_BRANCH: 'trunk'
    FEATURE_ALL: 'major'

stages:
    - Testing
    - Deploy

default:
    image: shopware/development:7.4-composer-2
    before_script:
        - zip -rq plugin.zip .
        - git clone --branch $DEVELOPMENT_BRANCH http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git
        - rm -rf development/platform
        - git clone --branch $PLATFORM_BRANCH http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform
        - unzip -q plugin.zip -d development/custom/plugins/SwagExtensionStore
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

ESLint:
    stage: Testing
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagExtensionStore/src/Resources/app/administration
        - npm ci
        - npm run lint-ci
    artifacts:
        when: always
        paths:
            - custom/plugins/SwagExtensionStore/src/Resources/app/administration/eslint.junit.xml
        reports:
            junit: $CI_PROJECT_DIR/development/custom/plugins/SwagExtensionStore/src/Resources/app/administration/eslint.junit.xml

Administration Jest:
    stage: Testing
    timeout: 1h 00m
    variables:
        PROJECT_ROOT: $CI_PROJECT_DIR/development
        PLUGINNAME: "SwagExtensionStore"
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:refresh
        - php bin/console plugin:install --activate $PLUGINNAME -c
        - npm --prefix $(pwd)/custom/plugins/$PLUGINNAME/src/Resources/app/administration/ ci
        - npm --prefix $(pwd)/vendor/shopware/platform/src/Administration/Resources/app/administration ci
        - ADMIN_PATH=$(pwd)/vendor/shopware/platform/src/Administration/Resources/app/administration/ npm --prefix $(pwd)/custom/plugins/$PLUGINNAME/src/Resources/app/administration/ run unit
    artifacts:
        reports:
            junit: development/build/artifacts/jest/customized-products.junit.xml

PHPUnit:
    stage: Testing
    timeout: 1h 00m
    variables:
        PROJECT_ROOT: $CI_PROJECT_DIR/development
        PLUGINNAME: "SwagExtensionStore"
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:refresh
        - php bin/console plugin:install --activate $PLUGINNAME -c
        - ./psh.phar init-test-databases
        - ./vendor/bin/phpunit -c $(pwd)/custom/plugins/$PLUGINNAME/phpunit.xml


Build Zip:
    stage: Deploy
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.0
        entrypoint: [""]
    variables:
        GIT_DEPTH: 0
    before_script: []
    script:
        - start-mysql
        - ln -s "$(pwd)" "/plugins/${CI_PROJECT_NAME}"
        - npm install --prefix src/Resources/app/administration/
        - pack-plugin "${CI_PROJECT_NAME}"
        - plugin-uploader ext:validate "$(realpath "SwagExtensionStore.zip")"
    artifacts:
        paths:
            - SwagExtensionStore*.zip

Upload Zip to Store:
    stage: Deploy
    only:
        refs:
        - master
    when: manual
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.0
        entrypoint: [""]
    variables:
        GIT_DEPTH: 0
    before_script: []
    script:
        - start-mysql
        - ln -s "$(pwd)" "/plugins/${CI_PROJECT_NAME}"
        - npm install --prefix src/Resources/app/administration/
        - pack-plugin "${CI_PROJECT_NAME}"
        - plugin-uploader ext:upload "$(realpath "SwagExtensionStore.zip")"

Update Store Information:
    stage: Deploy
    only:
        refs:
        - master
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.0
        entrypoint: [""]
    variables:
        GIT_DEPTH: 0
    before_script: []
    script:
        - plugin-uploader ext:update .
